// routes.js
export const ROUTES = {
    LOGIN: '/login',
    REGISTER: '/register',
    HOME: '/',
    DASHBOARD: '/dashboard',
    PRODUCTS: '/products',
    INVENTORY: '/inventory',
    SALES: '/sales',
    CHECKOUT: '/checkout',
    TRANSACTIONS: '/transactions',
    REPORTS: '/reports',
    USERS: '/users',
    SETTINGS: '/settings',
    CATEGORIES: '/categories',
    PRODUCT_DETAIL: '/products/:id',
    CREATE: '/create',
    CREATEPRODUCT: '/createproduct',
    ERROR: '/error',
    LOGOUT: '/logout',
};
